# Fichier de configuration pour Netlify pour un projet Next.js

[build]
  # La commande pour construire un projet Next.js est la même
  command = "npm run build"
  # Le dossier de sortie pour Next.js est ".next"
  publish = ".next"

# Plugin essentiel pour faire fonctionner Next.js sur Netlify
# Il gère les fonctions API, le rendu côté serveur, etc.
[[plugins]]
  package = "@netlify/plugin-nextjs"
