# Fichier de configuration pour Netlify pour un projet Create React App

[build]
  # Commande pour construire le site pour Create React App
  command = "npm run build"
  
  # Dossier qui contient le site buildé. Pour Create React App, c'est 'build'.
  publish = "build"
  
  # Dossier où se trouvent les fonctions serverless (API).
  # Netlify les trouvera automatiquement ici.
  functions = "api"

# Redirection pour que les appels /api/* pointent vers les fonctions serverless.
# C'est crucial pour que le backend fonctionne.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
